// Hand-written snapshot used until the pipeline writes real JSON into
// public/data/. Numbers (totals, by_company, remote_ratio) are derived by
// hand from the jobs list below — keep them consistent if you edit either.

import type { Snapshot } from "@/types/snapshot";

export const MOCK_SNAPSHOT: Snapshot = {
  meta: {
    date: "2026-05-17",
    totals: { companies: 2, jobs: 10, cities: 4, off_map: 0 },
  },
  cities: [
    {
      key: "san-francisco-ca-us",
      city: "San Francisco",
      state: "CA",
      country: "US",
      lat: 37.7749,
      lng: -122.4194,
      total: 4,
      by_company: { anthropic: 2, openai: 2 },
    },
    {
      key: "new-york-ny-us",
      city: "New York",
      state: "NY",
      country: "US",
      lat: 40.7128,
      lng: -74.006,
      total: 2,
      by_company: { anthropic: 1, openai: 1 },
    },
    {
      key: "london-gb",
      city: "London",
      state: null,
      country: "GB",
      lat: 51.5074,
      lng: -0.1278,
      total: 2,
      by_company: { anthropic: 1, openai: 1 },
    },
    {
      key: "singapore-sg",
      city: "Singapore",
      state: null,
      country: "SG",
      lat: 1.3521,
      lng: 103.8198,
      total: 2,
      by_company: { anthropic: 1, openai: 1 },
    },
  ],
  companies: [
    {
      slug: "anthropic",
      name: "Anthropic",
      total: 5,
      by_country: { US: 3, GB: 1, SG: 1 },
      top_cities: [
        { city: "San Francisco", count: 2 },
        { city: "New York", count: 1 },
        { city: "London", count: 1 },
        { city: "Singapore", count: 1 },
      ],
      remote_ratio: 0.2,
    },
    {
      slug: "openai",
      name: "OpenAI",
      total: 5,
      by_country: { US: 3, GB: 1, SG: 1 },
      top_cities: [
        { city: "San Francisco", count: 2 },
        { city: "New York", count: 1 },
        { city: "London", count: 1 },
        { city: "Singapore", count: 1 },
      ],
      remote_ratio: 0,
    },
  ],
  jobs: [
    {
      id: "anthropic-1",
      company: "anthropic",
      title: "Research Engineer, Interpretability",
      city: "San Francisco",
      country: "US",
      is_remote: false,
      team: "Research",
      posted_at: "2026-05-15",
      apply_url: "https://example.com/anthropic/jobs/1",
    },
    {
      id: "anthropic-2",
      company: "anthropic",
      title: "Software Engineer, Inference",
      city: "San Francisco",
      country: "US",
      is_remote: false,
      team: "Infrastructure",
      posted_at: "2026-05-14",
      apply_url: "https://example.com/anthropic/jobs/2",
    },
    {
      id: "anthropic-3",
      company: "anthropic",
      title: "Policy Analyst",
      city: "New York",
      country: "US",
      is_remote: true,
      team: "Policy",
      posted_at: "2026-05-12",
      apply_url: "https://example.com/anthropic/jobs/3",
    },
    {
      id: "anthropic-4",
      company: "anthropic",
      title: "Research Scientist, Alignment",
      city: "London",
      country: "GB",
      is_remote: false,
      team: "Research",
      posted_at: "2026-05-10",
      apply_url: "https://example.com/anthropic/jobs/4",
    },
    {
      id: "anthropic-5",
      company: "anthropic",
      title: "Policy Lead, APAC",
      city: "Singapore",
      country: "SG",
      is_remote: false,
      team: "Policy",
      posted_at: "2026-05-09",
      apply_url: "https://example.com/anthropic/jobs/5",
    },
    {
      id: "openai-1",
      company: "openai",
      title: "Member of Technical Staff, Training",
      city: "San Francisco",
      country: "US",
      is_remote: false,
      team: "Research",
      posted_at: "2026-05-16",
      apply_url: "https://example.com/openai/jobs/1",
    },
    {
      id: "openai-2",
      company: "openai",
      title: "Product Engineer, ChatGPT",
      city: "San Francisco",
      country: "US",
      is_remote: false,
      team: "Product",
      posted_at: "2026-05-13",
      apply_url: "https://example.com/openai/jobs/2",
    },
    {
      id: "openai-3",
      company: "openai",
      title: "Account Executive, Enterprise",
      city: "New York",
      country: "US",
      is_remote: false,
      team: "Sales",
      posted_at: "2026-05-11",
      apply_url: "https://example.com/openai/jobs/3",
    },
    {
      id: "openai-4",
      company: "openai",
      title: "Solutions Architect, EMEA",
      city: "London",
      country: "GB",
      is_remote: false,
      team: "Sales",
      posted_at: "2026-05-08",
      apply_url: "https://example.com/openai/jobs/4",
    },
    {
      id: "openai-5",
      company: "openai",
      title: "Software Engineer, Infrastructure",
      city: "Singapore",
      country: "SG",
      is_remote: false,
      team: "Infrastructure",
      posted_at: "2026-05-07",
      apply_url: "https://example.com/openai/jobs/5",
    },
  ],
};
